export default [
  { id: 1, name: "Aisha Khan", role: "Admin", active: true },
  { id: 2, name: "Ben Smith", role: "Developer", active: false },
  { id: 3, name: "Chloe Jones", role: "Designer", active: true },
  { id: 4, name: "Daniel Brown", role: "Developer", active: true },
  { id: 5, name: "Emily Wilson", role: "Designer", active: false },
  { id: 6, name: "Farhan Ali", role: "Developer", active: true },
  { id: 7, name: "Grace Taylor", role: "Admin", active: true },
  { id: 8, name: "Hassan Ahmed", role: "Developer", active: false },
  { id: 9, name: "Isabella Thomas", role: "Designer", active: true },
  { id: 10, name: "Jack White", role: "Developer", active: true },
  { id: 11, name: "Khadija Malik", role: "Admin", active: false },
  { id: 12, name: "Liam Johnson", role: "Developer", active: true },
  { id: 13, name: "Mia Davis", role: "Designer", active: true },
  { id: 14, name: "Noah Martin", role: "Developer", active: false },
  { id: 15, name: "Olivia Harris", role: "Designer", active: true },
  { id: 16, name: "Priya Patel", role: "Admin", active: true },
  { id: 17, name: "Quinn Walker", role: "Developer", active: true },
  { id: 18, name: "Ryan Lewis", role: "Developer", active: false },
  { id: 19, name: "Sophia Clark", role: "Designer", active: true },
  { id: 20, name: "Tariq Hussain", role: "Developer", active: true },
  { id: 21, name: "Uma Roberts", role: "Designer", active: false },
  { id: 22, name: "Victor Green", role: "Developer", active: true },
  { id: 23, name: "Will Evans", role: "Admin", active: true },
  { id: 24, name: "Xenia Moore", role: "Designer", active: true },
  { id: 25, name: "Yusuf Rahman", role: "Developer", active: false },
  { id: 26, name: "Zara Cooper", role: "Admin", active: true },
];
